import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import MCPClientWrapper from '../components/common/MCPClientWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
        style={{
          position: 'relative',
          margin: 0,
          padding: 0,
          minHeight: '100vh',
          backgroundColor: '#111'
        }}
      >
        {/* ここではクライアントコンポーネントを直接インポートできないため、
            下層のページコンポーネントに背景を表示させる */}
        {children}
        <MCPClientWrapper />
      </body>
    </html>
  );
}
